<a href="https://colab.research.google.com/github/Siddhant0609/python-learn/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np
arr=[1,3,57,85]
np_arr=np.array(arr)

In [ ]:
print(np_arr)

[ 1  3 57 85]


In [ ]:
type(np_arr)

numpy.ndarray

In [ ]:
ost=[1,2,44,56]
snd=[2,4,6,7,]
trd=[6,7,8,9]
matrix=np.array([ost,snd,trd])
print(matrix)

[[ 1  2 44 56]
 [ 2  4  6  7]
 [ 6  7  8  9]]


In [ ]:
matrix.shape

(3, 4)

In [ ]:
#indexing

In [ ]:
arr1=[1,2,5,7,8]
print(arr1[3])
num1=np.array(arr1)

7


In [ ]:
matrix

array([[ 1,  2, 44, 56],
       [ 2,  4,  6,  7],
       [ 6,  7,  8,  9]])

In [ ]:
print(matrix[0][0])

1


In [ ]:
matrix[1:,1:]

array([[4, 6, 7],
       [7, 8, 9]])

In [ ]:
#conditions in prepreocessing

In [ ]:
arr2

NameError: ignored

In [ ]:
num1[num1>2]

array([5, 7, 8])

In [ ]:
arr3=np.arange(1,11).reshape(2,5)
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
matrix.shape

(3, 4)

In [ ]:
matrix.reshape(4,3)

array([[ 1,  2, 44],
       [56,  2,  4],
       [ 6,  7,  6],
       [ 7,  8,  9]])